### ISSUE TITLE
[UX] Pressing Enter should register the task

### ISSUE THREAD

**Issue by RunAtTekky** [CompetitiveRohan/To--Do#2]
## Enter to register
Currently, I have to click the Add button to register the task.
Please add functionality to press enter and register the task.
![image](https://github.com/CompetitiveRohan/To--Do/assets/110292431/752bcce5-6870-4c03-900a-d277a990c414)

**Comment by Rohan-Singhh** [comment]
@RunAtTekky Thank you for the suggestion! I'll implement the Enter key functionality to register tasks soon.
